/**
 * Multi-Floor A* Indoor Router
 * Works on mapData generated by MapGenerator or loaded from Firebase.
 */
export class IndoorRouter {
  constructor(mapData) {
    this.nodes = new Map();
    this.adj = new Map();
    if (mapData) this.buildGraph(mapData);
  }

  buildGraph(mapData) {
    this.nodes.clear(); this.adj.clear();
    const { floors = {}, verticalTransit = [] } = mapData;

    // Index all waypoints
    for (const floorId in floors) {
      const f = floors[floorId];
      const fl = parseInt(floorId);
      for (const wp of (f.waypoints || [])) {
        this.nodes.set(wp.id, { id: wp.id, x: wp.x, y: wp.y, floor: fl,
          isElevator: !!wp.isElevator, isStairs: !!wp.isStairs, transitId: wp.transitId });
        if (!this.adj.has(wp.id)) this.adj.set(wp.id, []);
      }
      // Intra-floor edges
      for (const [u, v] of (f.connections || [])) {
        const nu = this.nodes.get(u), nv = this.nodes.get(v);
        if (!nu || !nv) continue;
        const d = Math.hypot(nu.x - nv.x, nu.y - nv.y);
        this.adj.get(u).push({ to: v, weight: d, type: "walk" });
        this.adj.get(v).push({ to: u, weight: d, type: "walk" });
      }
    }
    // Inter-floor edges
    for (const t of verticalTransit) {
      const nodeIds = Object.values(t.nodes);
      for (let i = 0; i < nodeIds.length; i++) {
        for (let j = i+1; j < nodeIds.length; j++) {
          if (!this.nodes.has(nodeIds[i]) || !this.nodes.has(nodeIds[j])) continue;
          const w = (t.transitionWeight || 20) * 10;
          this.adj.get(nodeIds[i]).push({ to: nodeIds[j], weight: w, type: t.type, label: t.name });
          this.adj.get(nodeIds[j]).push({ to: nodeIds[i], weight: w, type: t.type, label: t.name });
        }
      }
    }
  }

  findNearestWaypoint(x, y, floor) {
    let best = null, bestD = Infinity;
    for (const [, n] of this.nodes) {
      if (n.floor !== floor) continue;
      const d = Math.hypot(n.x - x, n.y - y);
      if (d < bestD) { bestD = d; best = n; }
    }
    return best;
  }

  findRoute(startPos, endPos) {
    const sNode = this.findNearestWaypoint(startPos.x, startPos.y, startPos.floor);
    const eNode = this.findNearestWaypoint(endPos.x, endPos.y, endPos.floor);
    if (!sNode || !eNode) return null;

    const open = new Set([sNode.id]);
    const cameFrom = new Map();
    const g = new Map([[sNode.id, 0]]);
    const f = new Map([[sNode.id, this._h(sNode, eNode)]]);

    while (open.size) {
      let curr = null, minF = Infinity;
      for (const id of open) { const s = f.get(id)??Infinity; if (s<minF){minF=s;curr=id;} }
      if (curr === eNode.id) return this._reconstruct(cameFrom, curr);
      open.delete(curr);
      for (const edge of (this.adj.get(curr)||[])) {
        const ng = (g.get(curr)??Infinity) + edge.weight;
        if (ng < (g.get(edge.to)??Infinity)) {
          cameFrom.set(edge.to, { from: curr, type: edge.type, label: edge.label });
          g.set(edge.to, ng);
          f.set(edge.to, ng + this._h(this.nodes.get(edge.to), eNode));
          open.add(edge.to);
        }
      }
    }
    return null;
  }

  _h(a, b) {
    if (!a || !b) return 0;
    return Math.hypot(a.x-b.x, a.y-b.y) + Math.abs(a.floor-b.floor)*500;
  }

  _reconstruct(cameFrom, curr) {
    const path = [this.nodes.get(curr)];
    const edges = [];
    while (cameFrom.has(curr)) {
      const e = cameFrom.get(curr); curr = e.from;
      path.unshift(this.nodes.get(curr)); edges.unshift(e);
    }
    let dist = 0;
    for (let i=0; i<path.length-1; i++) {
      if (path[i].floor === path[i+1].floor)
        dist += Math.hypot(path[i+1].x-path[i].x, path[i+1].y-path[i].y);
    }
    const instructions = this._makeInstructions(path, edges);
    return { path, totalDistanceMeters: Math.round(dist), estimatedTimeSeconds: Math.round(dist/1.3)+15, instructions };
  }

  _makeInstructions(path, edges) {
    const out = [];
    for (let i=0; i<path.length-1; i++) {
      const curr = path[i], next = path[i+1];
      if (curr.floor !== next.floor) {
        const up = next.floor > curr.floor;
        const via = curr.isElevator ? "Elevator" : "Staircase";
        out.push({ icon: curr.isElevator ? "🛗" : "🪜",
          text: `Take ${via} ${up?"up":"down"} to Floor ${next.floor}`, distance: 0, floor: curr.floor });
        continue;
      }
      const d = Math.round(Math.hypot(next.x-curr.x, next.y-curr.y));
      if (i===0) { out.push({ icon:"⬆️", text:`Head straight ${d}m`, distance:d, floor:curr.floor }); continue; }
      if (path[i-1].floor !== curr.floor) continue;
      const prev = path[i-1];
      const a1 = Math.atan2(curr.y-prev.y, curr.x-prev.x);
      const a2 = Math.atan2(next.y-curr.y, next.x-curr.x);
      let ang = (a2-a1)*180/Math.PI;
      while(ang>180)ang-=360; while(ang<-180)ang+=360;
      let icon="⬆️", text=`Continue straight ${d}m`;
      if(ang>35&&ang<145){icon="↗️";text=`Turn right, walk ${d}m`;}
      else if(ang<-35&&ang>-145){icon="↖️";text=`Turn left, walk ${d}m`;}
      else if(Math.abs(ang)>=145){icon="🔄";text=`U-turn, walk ${d}m`;}
      out.push({ icon, text, distance: d, floor: curr.floor });
    }
    out.push({ icon:"🏁", text:"You have arrived!", distance:0, floor:path[path.length-1].floor });
    return out;
  }
}
